package com.example.analytics.utils

object AnalyticsConstant {

    //    EVENT
    const val LANGUAGE_SELECTED = "LanguageSelected"
    const val LANGUAGE_NATIVE = "LanguageNative"
    const val HOME_NATIVE = "HomeNative"
    const val HOME_PREMIUM_ICON = "HomePremiumIcon"
    const val HOME_SETTINGS = "HomeSettings"
    const val HOME_GET_FREE_TRIAL = "HomeGetFreeTrial"
    const val HOME_EDIT = "HomeEdit"
    const val GALLERY_IMAGE_SELECTION = "GalleryImageSelection"
    const val GALLERY_NATIVE = "GalleryNative"
    const val GALLERY_CAMERA = "GalleryCamera"
    const val EDITOR_HOME_ICON = "EditorHomeIcon"
    const val EDITOR_TAP = "EditorTap"
    const val BTN_DOWNLOAD = "Download Button Clicked"
    const val EDITOR_SELECT = "EditorSelect"
    const val LINK_TO_SEARCH = "link"
    const val EDITOR_DESELECT = "EditorDeselect"
    const val EDITOR_BEFORE_AFTER = "EditorBeforeAfter"
    const val EDITOR_REDO = "EditorRedo"
    const val EDITOR_UNDO = "EditorUndo"
    const val EDITOR_SAVE = "EditorSave"
    const val EDITOR_DRAW_SELECT = "EditorDrawSelect"
    const val EDITOR_DRAW_DESELECT = "EditorDrawDeselect"
    const val RATING_STAR = "RatingStar"
    const val RATING_CLOSE = "RatingClose"
    const val RATING_PLAY_STORE = "RatingPlayStore"
    const val SAVE_DIALOG_NATIVE = "SaveDialogNative"
    const val SAVE_DIALOG_SAVE = "SaveDialogSave"
    const val SAVE_BS_PNG = "SaveBsPNG"
    const val SAVE_BS_PDF = "SaveBsPDF"
    const val SAVE_BS_SHARE = "SaveBsShare"
    const val SAVE_BS_CLOSE = "SaveBsClose"
    const val SETTINGS_7_DAYS_TRIAL = "Settings7DaysTrial"
    const val SETTINGS_REMOVE_ADS = "SettingsRemoveAds"
    const val SETTINGS_INSTAGRAM = "SettingsInstagram"
    const val SETTINGS_FACEBOOK = "SettingsFacebook"
    const val SETTINGS_RATE_US = "SettingsRateUs"
    const val SETTINGS_FEEDBACK = "SettingsFeedback"
    const val SETTINGS_CONTACT_US = "SettingsContactUs"
    const val SETTINGS_TERMS_CONDITION = "SettingsTermsConditions"
    const val SETTINGS_MANAGE_SUBSCRIPTION = "SettingsManageSubscription"
    const val DISCARD_DIALOG_NATIVE = "DiscardDialogNative"


    const val INAPP_PURCHASE = "InAppPurchase"
    const val INAPP_YEARLY_BUTTON_EVENT = "InAppYearlyButton"
    const val RATING = "Rating"
    const val MEDIA_PERMISSION = "MediaPermission"
    const val IMAGE_SAVED = "ImageSaved"
    const val EDITING_FEATURE = "EditingFeature"
    const val ENHANCE_FEATURE_SELECTION = "EnhanceFeatureSelection"
    const val ENHANCE_TUTORIAL = "EnhanceTutorial"
    const val REWARDED_AD = "RewardedAd"
    const val INTERSTITIAL_AD = "InterstitialAd"
    const val BANNER_AD = "BannerAd"
    const val AF_AD_VIEW = "af_ad_view"
    const val AF_SUBSCRIBE = "af_subscribe"
    const val FIT_SELECTION = "FitSelection"
    const val BACKDROP_SELECTION = "BackdropSelection"
    const val CLOTH_SELECTION = "ClothesSelection"
    const val APP_USERS = "app_user"
    const val FITLER_SELECTION = "FilterSelection"
    const val LIGHTFX_SELECTION = "LightFxSelection"
    const val STICKER_SLECTION = "StickerSelection"

    //PROPERTIES
    const val REW_AD_SAVE_IN_HD = "Rew_Ad_Save_in_HD"
    const val REMOVE_WM_PRO = "Remove_WM_Pro"
    const val REW_AD_REMOVE_WM = "Rew_Ad_Remove_WM"


    const val APP_OPEN_AD = "AppOpenAd"
    const val INTERSTITIAL = "Interstitial"
    const val REWARDED = "Rewarded"
    const val ADVERTISE_ID = "Advertiser ID"
    const val ACCEPTED = "Accepted"
    const val REJECTED = "Rejected"
    const val HOME = "Home"
    const val CROP = "Crop"
    const val FITLER = "Filter"
    const val LIGHTFX = "LightFx"
    const val FIT = "Fit"
    const val BACKDROP = "Backdrop"
    const val CLOTHES = "Clothes"
    const val STICKERS = "Stickers"
    const val TEXT = "text"
    const val ADJUST = "Adjust"
    const val SKY = "Sky"
    const val ENHANCE_SAVE = "EnhanceSave"
    const val IAP_DOWNLOAD_PDF = "IAP_Download_pdf"
    const val IAP_DOWNLOAD_PNG = "IAP_Download_png"
    const val OPENED = "opened"
    const val CLONE_STAMP_DONE ="clicked_on_done"
    const val SAVED = "saved"
    const val CLOSED = "closed"
    const val PARENT_EDITOR = "Parent_Editor"
    const val EDITOR = "Editor"
    const val ENHANCE = "Enhance"
    const val TUTORIAL = "Tutorial"
    const val COMPLETED = "completed"
    const val SHOWN = "shown"
    const val DRAWN = "drawn"

    const val FAILED = "failed"
    const val DISMISS = "dismiss"
    const val REMOVER = "Removers"
    const val EXISTING_USER = "existing user"
    const val RETURNING_USER = "returning user"

    const val HOME_ENHANCE_SELECTION = "homeEnhanceGallerySelection"
    const val HOME_EDITOR_SELECTION = "homeEditorSelection"
    const val HOME_EDITOR_GALLERY_SELECTION = "homeEditorGallerySelection"

    const val BACKDROP_CUSTOM_SELECTION = "backdropCustomSelection"
    const val CLOTHES_CUSTOM_SELECTION = "clothesCustomSelection"

    const val FILTER_THUMB_SELECTION = "filterThumbSelection"
    const val LIGHTFX_THUMB_SELECTION = "lightfxThumbSelection"
    const val STICKER_THUMB_SELECTION = "stickerThumbSelection"
    const val BACKDROP_THUMB_SELECTION = "backdropThumbSelection"
    const val CLOTHES_THUMB_SELECTION = "clothesThumbSelection"
    const val SKY_THUMB_SELECTION = "skyThumbSelection"

    const val BACKDROP_CATEGORY_SELECTION = "backdropCategorySelection"
    const val CLOTHES_CATEGORY_SELECTION = "clothesCategorySelection"
    const val SKY_CATEGORY_SELECTION = "skyCategorySelection"
    const val ADJUSTMENT_CATEGORY_SELECTION = "adjustmentCategorySelection"
    const val FIT_CATEGORY_SELECTION = "fitCategorySelection"
    const val CROP_CATEGORY_SELECTION = "cropCategorySelection"
    const val TEXT_CATEGORY_SELECTION = "textCategorySelection"

    const val CLONE_STAMP_FEATURE = "cloneStampFeature"


}